image: docker:latest
services:
  - docker:dind

stages:
  - build
  - package

build:
  image: gradle:5.0-jdk8-alpine
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - build/libs/*.jar

package:
  stage: package
  script:
    - docker build -t registry.gitlab.com/dormage/decentralized-orchestration-for-edge-computing .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/dormage/decentralized-orchestration-for-edge-computing
